version: 2
updates:
   - package-ecosystem: "npm"
     directory: "/"
     schedule:
        interval: "weekly"
        day: "thursday"
        time: "17:30"
        timezone: "Asia/Kolkata"
     reviewers:
        - "0xs1r4t"
     open-pull-requests-limit: 5
