import { type Metadata } from "next";
import "./globals.css";
import { AuthenticSans } from "@/fonts/font-config";

import { cn } from "@/lib/utils";
import SpotifyPlayer from "@/components/SpotifyPlayer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          AuthenticSans.className
        )}
      >
        {children}
        <SpotifyPlayer />
      </body>
    </html>
  );
};

export default RootLayout;
