import {
  generateTerrain,
  sampleHeight,
  type TerrainData,
} from "@/lib/garden/terrain";

/**
 * Garden configuration. The terrain is a rectangular heightfield slab
 * (per wireframe) generated by the ported terrain generator; the strip
 * camera stands on it at eye level looking toward the flower band.
 */
export const GARDEN = {
  terrain: {
    // 50×50 grid at 1.0 world units/cell → the original demo's footprint
    // (fairy-forest-glade main.cpp: Terrain(50, 50, 1.0f, 5.0f)).
    gridWidth: 50,
    gridHeight: 50,
    scale: 1.0,
    heightScale: 5.0,
    octaves: 6,
    // C++ terrain.h's frequency=0.05, sampled at frequency*1.5 in
    // terrain.cpp → effective 0.075/cell. Anything near 1.0+ makes
    // adjacent vertices sample near-uncorrelated noise (jittery bumps
    // instead of rolling hills) — this is the #1 cause of the shape drift
    // from the original. See docs/garden-webgpu-plan.md item 1.1.
    frequency: 0.075,
  },
  grass: {
    // ~30 instances/m² over the 50×50 slab, matching the original's
    // 300000 * areaRatio(50x50/100x100=0.25) = 75000.
    count: 75000,
    tuftWidth: 0.4, // fairy-forest-glade main.cpp: Foliage(..., height=0.8, width=0.4)
    tuftHeight: 0.8,
    slopeThreshold: 0.55,
    seed: 1,
  },
  flower: {
    width: 1.0, // fairy-forest-glade main.cpp: Foliage(..., height=1.0, width=1.0)
    height: 1.0,
    band: { zMin: 1.0, zMax: 5.0 }, // world z, in front of the strip camera
    maxHalfSpread: 13,
  },
  camera: {
    stripZ: 9.5, // strip camera stands here on the terrain
    eyeHeight: 1.9,
    targetZ: -1.5,
    targetHeight: 1.0,
    fov: 45,
  },
  wind: {
    speed: 1.2, // grass — fairy-forest-glade grass.vert: windSpeed=1.2, windStrength=0.25
    strength: 0.25,
    flowerSpeed: 0.8, // flowers are sturdier — fairy-forest-glade flower.vert: windSpeed=0.8, windStrength=0.15
    flowerStrength: 0.15,
  },
  fog: {
    // Exp²-fog density shared by every garden material. Light enough that
    // the terrain slab reads as an object when orbiting in immersive mode,
    // dense enough that the strip view melts into --color-background
    // before the far edge. Not in the C++ original (no fog there) — this
    // is a web-only concession for sitting the garden on the page.
    density: 0.045,
  },
} as const;

let cachedTerrain: TerrainData | null = null;

/** The garden's single terrain instance — deterministic, so cache it. */
export const getGardenTerrain = (): TerrainData => {
  if (!cachedTerrain) {
    const t = GARDEN.terrain;
    cachedTerrain = generateTerrain(
      t.gridWidth,
      t.gridHeight,
      t.scale,
      t.heightScale,
      t.octaves,
      t.frequency,
    );
  }
  return cachedTerrain;
};

/** Serializable subset of PostMetadata that crosses the server → client boundary. */
export interface GardenPost {
  slug: string;
  title: string;
  description: string;
  tags: string[];
  createdAt: string;
  status: string;
}

/** FNV-1a → [0, 1). Deterministic across builds/sessions. */
export const hashSlug = (slug: string): number => {
  let h = 0x811c9dc5;
  for (let i = 0; i < slug.length; i++) {
    h ^= slug.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0) / 4294967296;
};

export interface FlowerPlacement {
  slug: string;
  x: number;
  y: number; // terrain height at (x, z)
  z: number;
  /** deterministic per-post random: sway phase + rotation variation */
  rand: number;
  /** flower_1.png vs flower_2.png, decided by the slug */
  textureIndex: 0 | 1;
}

/**
 * One flower per post, spread across the strip's width.
 * Deterministic: each post gets an even slot (posts arrive sorted by
 * createdAt from getPublishedPosts), then its slug hash jitters it inside
 * the slot and picks its depth in the flower band — a slug always blooms
 * in the same place, rooted on the real terrain via sampleHeight.
 */
export const layoutFlowers = (
  posts: GardenPost[],
  terrain: TerrainData = getGardenTerrain(),
): FlowerPlacement[] => {
  const n = posts.length;
  if (n === 0) return [];

  const halfSpread = Math.min(
    GARDEN.flower.maxHalfSpread,
    Math.max(3.5, n * 1.15),
  );
  const slotWidth = (halfSpread * 2) / n;
  const { zMin, zMax } = GARDEN.flower.band;

  return posts.map((post, i) => {
    const hx = hashSlug(post.slug + ":x");
    const hz = hashSlug(post.slug + ":z");
    const rand = hashSlug(post.slug + ":r");

    const slotCenter = -halfSpread + slotWidth * (i + 0.5);
    const x = slotCenter + (hx - 0.5) * slotWidth * 0.8;
    const z = zMin + hz * (zMax - zMin);

    const sampled = sampleHeight(terrain, x, z);
    const y = sampled <= -999 ? 0 : sampled;

    return {
      slug: post.slug,
      x,
      y,
      z,
      rand,
      textureIndex: rand < 0.5 ? 0 : 1,
    };
  });
};
