import {
  generateTerrain,
  sampleHeight,
  type TerrainData,
} from "@/lib/garden/terrain";

/**
 * Garden configuration. The terrain is a rectangular heightfield slab
 * (per wireframe) generated by the ported terrain generator; the strip
 * camera stands on it at eye level looking toward the flower band.
 */
export const GARDEN = {
  terrain: {
    // 20×20 grid at 1.0 world units/cell → the original demo's footprint
    // (fairy-forest-glade main.cpp: Terrain(20, 20, 1.0f, 5.0f)).
    gridWidth: 20,
    gridHeight: 20,
    scale: 1.0,
    heightScale: 5.0,
    octaves: 6,
    // C++ terrain.h's frequency=0.05, sampled at frequency*1.5 in
    // terrain.cpp → effective 0.075/cell. Anything near 1.0+ makes
    // adjacent vertices sample near-uncorrelated noise (jittery bumps
    // instead of rolling hills) — this is the #1 cause of the shape drift
    // from the original. See docs/garden-webgpu-plan.md item 1.1.
    frequency: 0.2,
  },
  grass: {
    // instances/m² — matches the original's 300000 over its 100x100 demo
    // footprint (300000/10000=30/m²). Actual instance count is derived from
    // this times the current terrain's world-space area (width*scale ×
    // height*scale), so it stays correct as terrain size/scale change
    // instead of a literal tuned for one specific footprint (docs/features.md #2).
    density: 50,
    tuftWidth: 0.4, // fairy-forest-glade main.cpp: Foliage(..., height=0.8, width=0.4)
    tuftHeight: 0.8,
    slopeThreshold: 0.0, // slope threshold for grass placement (0.0 = everywhere)
    seed: 1,
  },
  flower: {
    width: 1.0, // fairy-forest-glade main.cpp: Foliage(..., height=1.0, width=1.0)
    height: 1.0,
    band: { zMin: 1.0, zMax: 5.0 }, // world z, in front of the strip camera
    maxHalfSpread: 13,
  },
  camera: {
    stripZ: 9.5, // strip camera stands here on the terrain
    eyeHeight: 1.9,
    targetZ: -1.5,
    targetHeight: 1.0,
    fov: 45,
  },
  wind: {
    speed: 1.2, // grass — fairy-forest-glade grass.vert: windSpeed=1.2, windStrength=0.25
    strength: 0.25,
    flowerSpeed: 0.8, // flowers are sturdier — fairy-forest-glade flower.vert: windSpeed=0.8, windStrength=0.15
    flowerStrength: 0.15,
  },
  fog: {
    // Linear near/far fog shared by every garden material: nothing closer
    // than `near` is fogged at all (the old exp²-density curve hazed even
    // foreground grass/flowers — see docs/features.md #1), then it ramps to
    // fully --color-background by `far`, melting the strip view into the
    // page before the terrain's edge. Not in the C++ original (no fog
    // there) — this is a web-only concession for sitting the garden on the
    // page.
    near: 5,
    far: 95,
  },
  trees: {
    // Not density-scaled from the C++ ratio (that gives ~2 trees on this
    // terrain's 20×20 footprint, too sparse to read as trees) — a small
    // fixed count picked to frame a small hero garden instead.
    count: 7,
    // fairy-forest-glade tree_manager.cpp's distScale(2,4) was calibrated
    // for its 100×100 placement terrain (distX/distZ(-50,50)) — scaled down
    // by this terrain's 20×20 footprint (0.2x linear) so a ~4.7-unit-tall
    // unscaled branch model (confirmed by inspecting the converted .glb's
    // vertex bounds) reads as a tree framing a small garden, not a giant
    // dwarfing it. 0.4-0.8 -> ~1.9-3.8 units tall, comparable to the
    // terrain's own heightScale=5 relief.
    scaleRange: [0.4, 0.8] as [number, number],
    minSpacing: 4.0, // fairy-forest-glade tree_manager.cpp: minSpacing=4.0f
    slopeThreshold: 0.7, // fairy-forest-glade tree_manager.cpp: normal.y > 0.7f
    // Camera-corridor exclusion (plan item 4.4): the strip camera looks
    // straight down -z from x≈0, so a full-depth center-strip exclusion —
    // not a C++-style bounded wedge — is what actually keeps the hero view
    // clear at any depth.
    corridorHalfWidth: 4,
    // Catches trees that clear the corridor's x-check but still land right
    // next to the camera (verified visually — see placeTrees's comment).
    cameraExclusionRadius: 6,
    flowerExclusionRadius: 2,
    // GenerateLeafClusters(clustersPerBranch, leavesPerCluster) — same
    // per-type params as fairy-forest-glade main.cpp.
    normal: { clustersPerBranch: 12, leavesPerCluster: 20 },
    thick: { clustersPerBranch: 16, leavesPerCluster: 24 },
    leafSeed: 42, // fairy-forest-glade tree_foliage.cpp: mt19937 rng(42)
    placementSeed: 7,
  },
} as const;

let cachedTerrain: TerrainData | null = null;

/** The garden's single terrain instance — deterministic, so cache it. */
export const getGardenTerrain = (): TerrainData => {
  if (!cachedTerrain) {
    const t = GARDEN.terrain;
    cachedTerrain = generateTerrain(
      t.gridWidth,
      t.gridHeight,
      t.scale,
      t.heightScale,
      t.octaves,
      t.frequency,
    );
  }
  return cachedTerrain;
};

/** Serializable subset of PostMetadata that crosses the server → client boundary. */
export interface GardenPost {
  slug: string;
  title: string;
  description: string;
  tags: string[];
  createdAt: string;
  status: string;
}

/** FNV-1a → [0, 1). Deterministic across builds/sessions. */
export const hashSlug = (slug: string): number => {
  let h = 0x811c9dc5;
  for (let i = 0; i < slug.length; i++) {
    h ^= slug.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0) / 4294967296;
};

/** One flower's world-space position and deterministic per-post variation. */
export interface FlowerPlacement {
  slug: string;
  x: number;
  y: number; // terrain height at (x, z)
  z: number;
  /** deterministic per-post random: sway phase + rotation variation */
  rand: number;
  /** flower_1.png vs flower_2.png, decided by the slug */
  textureIndex: 0 | 1;
}

/**
 * One flower per post, spread across the strip's width.
 * Deterministic: each post gets an even slot (posts arrive sorted by
 * createdAt from getPublishedPosts), then its slug hash jitters it inside
 * the slot and picks its depth in the flower band — a slug always blooms
 * in the same place, rooted on the real terrain via sampleHeight.
 */
export const layoutFlowers = (
  posts: GardenPost[],
  terrain: TerrainData = getGardenTerrain(),
): FlowerPlacement[] => {
  const n = posts.length;
  if (n === 0) return [];

  const halfSpread = Math.min(
    GARDEN.flower.maxHalfSpread,
    Math.max(3.5, n * 1.15),
  );
  const slotWidth = (halfSpread * 2) / n;
  const { zMin, zMax } = GARDEN.flower.band;

  return posts.map((post, i) => {
    const hx = hashSlug(post.slug + ":x");
    const hz = hashSlug(post.slug + ":z");
    const rand = hashSlug(post.slug + ":r");

    const slotCenter = -halfSpread + slotWidth * (i + 0.5);
    const x = slotCenter + (hx - 0.5) * slotWidth * 0.8;
    const z = zMin + hz * (zMax - zMin);

    const sampled = sampleHeight(terrain, x, z);
    const y = sampled <= -999 ? 0 : sampled;

    return {
      slug: post.slug,
      x,
      y,
      z,
      rand,
      textureIndex: rand < 0.5 ? 0 : 1,
    };
  });
};
